# This file provides instructions for packaging.

`Lingua-Boolean-Tiny`
	deps:runtime-requirement [ deps:on "perl 5.006002"^^deps:CpanId ];
	deps:test-requirement    [ deps:on "Test::More"^^deps:CpanId ];
	.

