# This file provides instructions for packaging.

`Lingua-Boolean-Tiny`
	perl_version_from m`Lingua::Boolean::Tiny`;
	version_from      m`Lingua::Boolean::Tiny`;
	readme_from       m`Lingua::Boolean::Tiny`;
.

